// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    CarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    CarbonLanguage: typeof import('~icons/carbon/language')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonMusic: typeof import('~icons/carbon/music')['default']
    CarbonPedestrian: typeof import('~icons/carbon/pedestrian')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    CarbonWarning: typeof import('~icons/carbon/warning')['default']
    Counter: typeof import('./counter/components/Counter.vue')['default']
    Footer: typeof import('./common/components/Footer.vue')['default']
    PlanItem: typeof import('./orders/components/PlanItem.vue')['default']
    README: typeof import('./common/components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VButton: typeof import('./common/components/VButton.vue')['default']
    VButtonText: typeof import('./common/components/VButtonText.vue')['default']
    VDescription: typeof import('./common/components/VDescription.vue')['default']
    VInput: typeof import('./common/components/VInput.vue')['default']
    VTitleLg: typeof import('./common/components/VTitleLg.vue')['default']
  }
}
